import type { BaseItem, CraftTarget, CurrencyPrices, DataSource, IdealModifierSet, ItemProfile, Mod } from "./types.js";
import { parseBaseItem, parseCraftTarget, parseIdealModifierSet, parseItemProfile, parseMods } from "./schema.js";

function poe2dbSource(ref: string, path: string): DataSource {
  return {
    provider: "poe2db",
    ref,
    url: `https://poe2db.tw/us/${path}`,
  };
}

export const voltaicStaff: BaseItem = parseBaseItem({
  id: "voltaic_staff",
  name: "Voltaic Staff",
  itemClass: "staff",
  tags: [
    "staff",
    "twohand",
    "no_fire_spell_mods",
    "no_cold_spell_mods",
    "no_chaos_spell_mods",
    "no_physical_spell_mods",
  ],
  source: poe2dbSource("Metadata/Items/Weapons/TwoHandWeapons/Staves/VoltaicStaff", "Voltaic_Staff"),
  priceSource: poe2dbSource("Voltaic Staff", "Voltaic_Staff"),
});

export const staffMods: Mod[] = parseMods([
  {
    id: "stormbound_t1",
    name: "Stormbound",
    text: "Gain (55-60)% of Damage as Extra Lightning Damage",
    affix: "prefix",
    level: 80,
    tier: 1,
    families: ["extra_lightning_damage"],
    itemClasses: ["staff"],
    weight: 1,
    group: "extra_damage",
    source: poe2dbSource("stormbound_t1", "Modifiers"),
  },
  {
    id: "stormbound_t2",
    name: "Stormbound",
    text: "Gain (48-54)% of Damage as Extra Lightning Damage",
    affix: "prefix",
    level: 72,
    tier: 2,
    families: ["extra_lightning_damage"],
    itemClasses: ["staff"],
    weight: 2,
    group: "extra_damage",
    source: poe2dbSource("stormbound_t2", "Modifiers"),
  },
  {
    id: "of_assimilation_t1",
    name: "of Assimilation",
    text: "Gain (36-45) Mana per enemy killed",
    affix: "suffix",
    level: 78,
    tier: 1,
    families: ["mana_on_kill"],
    itemClasses: ["staff"],
    weight: 1,
    group: "mana_on_kill",
    source: poe2dbSource("of_assimilation_t1", "Modifiers"),
  },
  {
    id: "of_assimilation_t2",
    name: "of Assimilation",
    text: "Gain (28-35) Mana per enemy killed",
    affix: "suffix",
    level: 70,
    tier: 2,
    families: ["mana_on_kill"],
    itemClasses: ["staff"],
    weight: 2,
    group: "mana_on_kill",
    source: poe2dbSource("of_assimilation_t2", "Modifiers"),
  },
  {
    id: "charged_t1",
    name: "Charged",
    text: "(90-109)% increased Lightning Damage",
    affix: "prefix",
    level: 76,
    tier: 1,
    families: ["lightning_damage"],
    itemClasses: ["staff"],
    weight: 4,
    group: "elemental_damage",
    source: poe2dbSource("charged_t1", "Modifiers"),
  },
  {
    id: "of_the_storm_t1",
    name: "of the Storm",
    text: "(18-22)% increased Cast Speed",
    affix: "suffix",
    level: 75,
    tier: 1,
    families: ["cast_speed"],
    itemClasses: ["staff"],
    weight: 4,
    group: "cast_speed",
    source: poe2dbSource("of_the_storm_t1", "Modifiers"),
  },
  {
    id: "arcane_t1",
    name: "Arcane",
    text: "(120-139)% increased Spell Damage",
    affix: "prefix",
    level: 78,
    tier: 1,
    families: ["spell_damage"],
    itemClasses: ["staff"],
    blockedByTags: ["no_lightning_spell_mods"],
    weight: 4,
    group: "spell_damage",
    source: poe2dbSource("arcane_t1", "Modifiers"),
  },
  {
    id: "of_conservation_t1",
    name: "of Conservation",
    text: "(20-24)% reduced Mana Cost of Skills",
    affix: "suffix",
    level: 74,
    tier: 1,
    families: ["mana_cost"],
    itemClasses: ["staff"],
    weight: 4,
    group: "mana_cost",
    source: poe2dbSource("of_conservation_t1", "Modifiers"),
  },
]);

export const expertShortbow: BaseItem = parseBaseItem({
  id: "expert_shortbow",
  name: "Expert Shortbow",
  itemClass: "bow",
  tags: ["bow", "ranged", "attack"],
  source: poe2dbSource("Metadata/Items/Weapons/OneHandWeapons/Bows/ExpertShortbow", "Expert_Shortbow"),
  priceSource: poe2dbSource("Expert Shortbow", "Expert_Shortbow"),
});

export const bowMods: Mod[] = parseMods([
  {
    id: "sharpshooters_t1",
    name: "Sharpshooter's",
    text: "(135-154)% increased Physical Damage",
    affix: "prefix",
    level: 78,
    tier: 1,
    families: ["physical_damage"],
    itemClasses: ["bow"],
    weight: 4,
    group: "physical_damage",
    source: poe2dbSource("sharpshooters_t1", "Modifiers"),
  },
  {
    id: "merciless_t2",
    name: "Merciless",
    text: "(110-134)% increased Physical Damage",
    affix: "prefix",
    level: 70,
    tier: 2,
    families: ["physical_damage"],
    itemClasses: ["bow"],
    weight: 8,
    group: "physical_damage",
    source: poe2dbSource("merciless_t2", "Modifiers"),
  },
  {
    id: "of_celebration_t1",
    name: "of Celebration",
    text: "(24-27)% increased Attack Speed",
    affix: "suffix",
    level: 76,
    tier: 1,
    families: ["attack_speed"],
    itemClasses: ["bow"],
    weight: 4,
    group: "attack_speed",
    source: poe2dbSource("of_celebration_t1", "Modifiers"),
  },
  {
    id: "of_accuracy_t1",
    name: "of Accuracy",
    text: "+(401-500) to Accuracy Rating",
    affix: "suffix",
    level: 75,
    tier: 1,
    families: ["accuracy"],
    itemClasses: ["bow"],
    weight: 6,
    group: "accuracy",
    source: poe2dbSource("of_accuracy_t1", "Modifiers"),
  },
  {
    id: "crackling_t1",
    name: "Crackling",
    text: "Adds 1 to 120 Lightning Damage",
    affix: "prefix",
    level: 72,
    tier: 1,
    families: ["lightning_damage"],
    itemClasses: ["bow"],
    weight: 6,
    group: "added_lightning_damage",
    source: poe2dbSource("crackling_t1", "Modifiers"),
  },
  {
    id: "of_puncturing_t1",
    name: "of Puncturing",
    text: "+(31-35)% to Critical Hit Chance",
    affix: "suffix",
    level: 78,
    tier: 1,
    families: ["critical_chance"],
    itemClasses: ["bow"],
    weight: 4,
    group: "critical_chance",
    source: poe2dbSource("of_puncturing_t1", "Modifiers"),
  },
]);

export const expertHexersRobe: BaseItem = parseBaseItem({
  id: "expert_hexers_robe",
  name: "Expert Hexer's Robe",
  itemClass: "body_armour",
  tags: ["body_armour", "int_armour", "caster"],
  source: poe2dbSource("Metadata/Items/Armours/BodyArmours/ExpertHexersRobe", "Expert_Hexer%27s_Robe"),
  priceSource: poe2dbSource("Expert Hexer's Robe", "Expert_Hexer%27s_Robe"),
});

export const robeMods: Mod[] = parseMods([
  {
    id: "sages_t1",
    name: "Sage's",
    text: "+(121-150) to maximum Mana",
    affix: "prefix",
    level: 76,
    tier: 1,
    families: ["maximum_mana"],
    itemClasses: ["body_armour"],
    weight: 6,
    group: "maximum_mana",
    source: poe2dbSource("sages_t1", "Modifiers"),
  },
  {
    id: "warding_t1",
    name: "Warding",
    text: "+(101-120) to maximum Energy Shield",
    affix: "prefix",
    level: 75,
    tier: 1,
    families: ["energy_shield"],
    itemClasses: ["body_armour"],
    weight: 6,
    group: "energy_shield",
    source: poe2dbSource("warding_t1", "Modifiers"),
  },
  {
    id: "of_the_order_t1",
    name: "of the Order",
    text: "+(31-35)% to all Elemental Resistances",
    affix: "suffix",
    level: 78,
    tier: 1,
    families: ["elemental_resistance"],
    itemClasses: ["body_armour"],
    weight: 4,
    group: "elemental_resistance",
    source: poe2dbSource("of_the_order_t1", "Modifiers"),
  },
  {
    id: "of_the_walrus_t1",
    name: "of the Walrus",
    text: "+(101-120) to maximum Life",
    affix: "suffix",
    level: 76,
    tier: 1,
    families: ["maximum_life"],
    itemClasses: ["body_armour"],
    weight: 6,
    group: "maximum_life",
    source: poe2dbSource("of_the_walrus_t1", "Modifiers"),
  },
  {
    id: "scholars_t1",
    name: "Scholar's",
    text: "+(31-35) to Intelligence",
    affix: "suffix",
    level: 74,
    tier: 1,
    families: ["intelligence"],
    itemClasses: ["body_armour"],
    weight: 6,
    group: "attribute",
    source: poe2dbSource("scholars_t1", "Modifiers"),
  },
  {
    id: "incandescent_t1",
    name: "Incandescent",
    text: "(91-100)% increased Energy Shield",
    affix: "prefix",
    level: 78,
    tier: 1,
    families: ["increased_energy_shield"],
    itemClasses: ["body_armour"],
    weight: 4,
    group: "defences_percent",
    source: poe2dbSource("incandescent_t1", "Modifiers"),
  },
]);

export const idealModifierSets: IdealModifierSet[] = [
  parseIdealModifierSet({
    id: "voltaic-extra-lightning-mana",
    name: "Extra lightning + mana sustain",
    description: "Two-mod magic target for early route comparison.",
    baseItemId: voltaicStaff.id,
    itemLevel: 80,
    targets: [
      {
        affix: "prefix",
        exactTier: 1,
        textIncludes: "Gain (55-60)% of Damage as Extra Lightning Damage",
      },
      {
        affix: "suffix",
        exactTier: 1,
        textIncludes: "Mana per enemy killed",
      },
    ],
    source: poe2dbSource("voltaic-extra-lightning-mana", "Modifiers"),
  }),
  parseIdealModifierSet({
    id: "voltaic-lightning-cast-speed",
    name: "Lightning damage + cast speed",
    description: "Rare-capable damage profile using poe2db visible modifier rows.",
    baseItemId: voltaicStaff.id,
    itemLevel: 80,
    targets: [
      {
        affix: "prefix",
        exactTier: 1,
        textIncludes: "increased Lightning Damage",
      },
      {
        affix: "suffix",
        exactTier: 1,
        textIncludes: "increased Cast Speed",
      },
    ],
    source: poe2dbSource("voltaic-lightning-cast-speed", "Modifiers"),
  }),
];

export const bowIdealModifierSets: IdealModifierSet[] = [
  parseIdealModifierSet({
    id: "bow-phys-speed",
    name: "Physical DPS + speed",
    description: "Core physical bow prefix plus attack speed suffix.",
    baseItemId: expertShortbow.id,
    itemLevel: 80,
    targets: [
      {
        affix: "prefix",
        exactTier: 1,
        textIncludes: "increased Physical Damage",
      },
      {
        affix: "suffix",
        exactTier: 1,
        textIncludes: "increased Attack Speed",
      },
    ],
    source: poe2dbSource("bow-phys-speed", "Modifiers"),
  }),
  parseIdealModifierSet({
    id: "bow-lightning-crit",
    name: "Lightning + crit",
    description: "Elemental hit profile with crit chance.",
    baseItemId: expertShortbow.id,
    itemLevel: 80,
    targets: [
      {
        affix: "prefix",
        exactTier: 1,
        textIncludes: "Adds 1 to 120 Lightning Damage",
      },
      {
        affix: "suffix",
        exactTier: 1,
        textIncludes: "Critical Hit Chance",
      },
    ],
    source: poe2dbSource("bow-lightning-crit", "Modifiers"),
  }),
];

export const robeIdealModifierSets: IdealModifierSet[] = [
  parseIdealModifierSet({
    id: "robe-mana-resists",
    name: "Mana + elemental resists",
    description: "Caster defensive set for mana and resist coverage.",
    baseItemId: expertHexersRobe.id,
    itemLevel: 80,
    targets: [
      {
        affix: "prefix",
        exactTier: 1,
        textIncludes: "maximum Mana",
      },
      {
        affix: "suffix",
        exactTier: 1,
        textIncludes: "Elemental Resistances",
      },
    ],
    source: poe2dbSource("robe-mana-resists", "Modifiers"),
  }),
  parseIdealModifierSet({
    id: "robe-energy-shield-life",
    name: "Energy shield + life",
    description: "Hybrid survival set with flat energy shield and life.",
    baseItemId: expertHexersRobe.id,
    itemLevel: 80,
    targets: [
      {
        affix: "prefix",
        exactTier: 1,
        textIncludes: "maximum Energy Shield",
      },
      {
        affix: "suffix",
        exactTier: 1,
        textIncludes: "maximum Life",
      },
    ],
    source: poe2dbSource("robe-energy-shield-life", "Modifiers"),
  }),
];

export const staffTarget: CraftTarget = parseCraftTarget({
  base: "Voltaic Staff",
  itemLevel: idealModifierSets[0].itemLevel,
  targets: idealModifierSets[0].targets,
  mode: "contains-mods",
  allowExtraMods: true,
});

export const itemProfiles: ItemProfile[] = [
  parseItemProfile({
    id: "voltaic-staff",
    baseItem: voltaicStaff,
    mods: staffMods,
    idealModifierSets,
  }),
  parseItemProfile({
    id: "expert-shortbow",
    baseItem: expertShortbow,
    mods: bowMods,
    idealModifierSets: bowIdealModifierSets,
  }),
  parseItemProfile({
    id: "expert-hexers-robe",
    baseItem: expertHexersRobe,
    mods: robeMods,
    idealModifierSets: robeIdealModifierSets,
  }),
];

export const samplePrices: CurrencyPrices = {
  transmute: 0.05,
  "greater-transmute": 1,
  "perfect-transmute": 3,
  augment: 0.05,
  "greater-augment": 2,
  "perfect-augment": 8,
  regal: 0.5,
  "greater-regal": 1,
  "perfect-regal": 3,
  "omen-sinistral-coronation": 1,
  "omen-dextral-coronation": 1,
  alchemy: 0.86,
  "omen-sinistral-alchemy": 1,
  "omen-dextral-alchemy": 1,
  exalt: 1,
  "greater-exalt": 2,
  "perfect-exalt": 6,
  "omen-sinistral-exaltation": 1,
  "omen-dextral-exaltation": 1,
  "omen-greater-exaltation": 1,
};
